site_name: wadamczyk's space
use_directory_urls: false
theme: 
  name: material
  logo: 'assets/images/atom.png'
  favicon: 'assets/images/atom_fav.png'
  palette:
    primary: 'white'
    accent: 'blue'
  features:
    - navigation.top
    - navigation.tabs
    - toc.integrate  # This integrates TOC into the left sidebar


nav:
  - Abstract: index.md
  - "Teaching":
    - "Quantum Information Processing - Concepts":
      - "Chapter 0: Introduction": teaching/quantum_information_processing/index.md
      - "Chapter 1a: Principles of Quantum Mechanics": teaching/quantum_information_processing/chapters/01a_principles_of_quantum_mechanics.md
      - "Chapter 1b: Toolbox": teaching/quantum_information_processing/chapters/01b_toolbox.md
      # - "Chapter 2a: Quantum Information Theory": teaching/quantum_information_processing/chapters/02a_quantum_information.md
      - "Chapter 3a: Computational Complexity": teaching/quantum_information_processing/chapters/03a_computational_complexity.md
      - "Chapter 3b: Universal gates, Reversible irreversability, Oracle Functions": teaching/quantum_information_processing/chapters/03b_universal_gates_and_oracles.md
      - "Chapter 4a: DJ style algorithms": teaching/quantum_information_processing/chapters/04a_deutsch_jozsa_algorithms.md
      - "Chapter 4b: Grover's algorithm": teaching/quantum_information_processing/chapters/04b_grovers_algorithm.md
      - "Chapter 4c: Quantum Fourier Transform, Period Finding Algorithm": teaching/quantum_information_processing/chapters/04c_quantum_fourier_transform.md
      - "Chapter 5: Shor's Algorithm": teaching/quantum_information_processing/chapters/05_shors_algorithm.md
      - "Chapter 6: Open Quantum Systems": teaching/quantum_information_processing/chapters/06_open_quantum_systems.md
      - "Chapter 7: Quantum Error Correction": teaching/quantum_information_processing/chapters/07_quantum_error_correction.md
      - "Chapter 8: Stabiliser Formalism": teaching/quantum_information_processing/chapters/08_stabiliser_formalism.md
  - "Random Walk":
    - "Quantum Optics":
      - "Light-Matter Interaction": random_walk/quantum_optics/rabi_frequencies.md
    - "Classical Optics":
      - "Aberration propagator": random_walk/classical_optics/aberrations/index.md
    - "Simulations":
      - "EMCCD Camera": random_walk/simulations/emccd_camera.md
  - "Courses":
    - "Scientific Writing Workshop": courses/scientific_writing_workshop/index.md
  - "Projects":
    - "ekoAcademic":
      - "about": projects/ekoacademic/index.md
    - "Atomphys":
      - "about": projects/atomphys/index.md
    - "MUD":
      - "about": projects/mud/index.md

# Plugins (optional)
plugins:
  - search

hooks:
  - hooks/redirects.py

extra_css:
  - 'assets/stylesheets/extra.css'


# Markdown Extensions
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - assets/javascripts/collapse-nav.js
